
obj-y += ci20-misc.o ci20-pm.o ci20-lcd.o

obj-$(CONFIG_I2C)		+= ci20-i2c.o
obj-$(CONFIG_MFD_ACT8600)	+= ci20-regulator.o
obj-$(CONFIG_MMC_JZ4780)	+= ci20-mmc.o
obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += ci20-sound.o
obj-$(CONFIG_NAND_JZ4780)	+= ci20-nand.o
obj-$(CONFIG_MTD_NAND_JZ4780)	+= ci20-nand-mtd.o
