obj-$(CONFIG_HDMI_JZ4780) += \
speakerAllocationDataBlock.o \
shortAudioDesc.o \
halEdid.o \
videoCapabilityDataBlock.o \
monitorRangeLimits.o \
colorimetryDataBlock.o \
hdmivsdb.o \
edid.o \
dtd.o \
shortVideoDesc.o
