obj-$(CONFIG_HDMI_JZ4780)	+= jz4780_hdmi.o
obj-$(CONFIG_HDMI_JZ4780)	+= api/
obj-$(CONFIG_HDMI_JZ4780)	+= core/
obj-$(CONFIG_HDMI_JZ4780)	+= hdcp/
obj-$(CONFIG_HDMI_JZ4780)	+= phy/
obj-$(CONFIG_HDMI_JZ4780)	+= edid/
obj-$(CONFIG_HDMI_JZ4780)	+= bsp/
obj-$(CONFIG_HDMI_JZ4780)	+= util/
