
obj-y += npm709J-misc.o npm709J-pm.o npm709J-lcd.o  

obj-$(CONFIG_I2C)		+= npm709J-i2c.o
obj-$(CONFIG_MFD_ACT8600)	+= npm709J-regulator.o
obj-$(CONFIG_MMC_JZ4780)	+= npm709J-mmc.o
obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += npm709J-sound.o
obj-$(CONFIG_NAND_JZ4780)	+= npm709J-nand.o
obj-$(CONFIG_JZ_MODEM)		+= npm709J-modem.o
obj-$(CONFIG_BCM4330_RFKILL) += npm709J-bt.o
