#
# Ingenic JZ4780 ASoC makefile
#
# Copyright (c) 2013 Imagination Technologies
# Author: Paul Burton <paul.burton@imgtec.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

obj-$(CONFIG_SND_JZ4780_SOC)		+= jz4780-pcm.o
obj-$(CONFIG_SND_JZ4780_SOC_I2S)	+= jz4780-i2s.o
obj-$(CONFIG_SND_JZ4780_SOC_CI20)	+= ci20.o
